before_script:
    - wget https://nodejs.org/dist/v8.11.4/node-v8.11.4-linux-x64.tar.xz
    - tar xf node-v8.11.4-linux-x64.tar.xz
    - PATH="$PATH:$(pwd)/node-v8.11.4-linux-x64/bin"
    - npm install -g eslint

eslint:
    stage: test
    script:
        - eslint .
