MazeLike_Eslint:
  image: node:8.11
  stage: test
  script:
    - npm install -dd
    - npm run eslint

MazeLike_Tests:
  image: node:8.11
  stage: test
  script:
    - curl -fsSL https://get.docker.com | bash && \
    - curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker    -compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    - chmod +x /usr/local/bin/docker-compose
    - npm test

MazeLike_Deploy:
  image: docker:stable
  stage: deploy
  script:
      # Version parser from https://gist.github.com/DarrenN/8c6a5b969481725a4413
      - "VERSION=$(cat package.json | grep version | head -1  | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
      - docker build -t "mazelike/backend:$VERSION" .
      - docker tag "mazelike/backend:$VERSION" mazelike/backend:latest
      - docker kill mazelike || echo "Server not running"
      - docker container rm mazelike || echo "Container not found"
      - docker run --name mazelike -d -p 80:3000 --env-file /etc/mazelike/.env "mazelike/backend:$VERSION"
  only:
    - master