MazeLike_Testing:
  image: node:8.11
  stage: test
  script:
    - npm install -dd
    - npm run eslint
    - npm test

MazeLike_Deploy:
  image: docker:stable
  stage: deploy
  script:
      - docker build -t mazelike/backend .
      - docker kill mazelike || echo "Server not running"
      - docker container rm mazelike || echo "Container not found"
      - docker run --name mazelike -d -p 80:3000 -e NODE_ENV=production mazelike/backend
