stages:
  - build
  - test
  - cleanup
  - deploy

Build:
  stage: build
  script:
    - BRANCH=$(echo $CI_COMMIT_REF_NAME | cut -c 1-15)
    - sed s/branch/$BRANCH/ -i docker-compose.yml
    - sed s/latest/branch-$BRANCH/ -i docker-compose.yml
    - docker-compose build
    - docker-compose up -d backend

Eslint:
  stage: test
  script:
    - npm run eslint

Backend_Tests:
  stage: test
  script:
    - BRANCH=$(echo $CI_COMMIT_REF_NAME | cut -c 1-15)
    - sed s/branch/$BRANCH/ -i docker-compose.yml
    - sed s/latest/branch-$BRANCH/ -i docker-compose.yml
    - touch runner-result
    - chmod 666 runner-result
    - docker-compose up -d tests_backend
    - node scripts/test-stopper.js tests_backend

Browser_Tests:
  stage: test
  script:
    - BRANCH=$(echo $CI_COMMIT_REF_NAME | cut -c 1-15)
    # Version parser from https://gist.github.com/DarrenN/8c6a5b969481725a4413
    - sed s/branch/$BRANCH/ -i docker-compose.yml
    - sed s/latest/branch-$BRANCH/ -i docker-compose.yml
    - touch runner-result
    - chmod 666 runner-result
    - docker-compose up -d tests_browser
    - node scripts/test-stopper.js tests_browser

Version_Change:
  stage: test
  allow_failure: true
  script:
    - node scripts/version-check.js

Cleanup:
  stage: cleanup
  when: always
  script:
    - BRANCH=$(echo $CI_COMMIT_REF_NAME | cut -c 1-15)
    - sed s/branch/$BRANCH/ -i docker-compose.yml
    - docker-compose down

Deploy:
  stage: deploy
  script:
    - BRANCH=$(echo $CI_COMMIT_REF_NAME | cut -c 1-15)
    - VERSION=$(cat VERSION)
    - node scripts/version-check.js
    - docker tag ryan3r/mazelike:branch-$BRANCH ryan3r/mazelike:$VERSION
    - deploy $VERSION
    - docker tag ryan3r/mazelike:$VERSION ryan3r/mazelike:latest
  only:
    - master
