# MazeLike_Tests:
#   stage: test
#   script:

MazeLike_Deploy:
  stage: deploy
  script:
      # Version parser from https://gist.github.com/DarrenN/8c6a5b969481725a4413
      - "VERSION=$(cat package.json | grep version | head -1  | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
      - docker build -t "mazelike/backend:$VERSION" .
      - docker tag "mazelike/backend:$VERSION" mazelike/backend:latest
      - docker kill mazelike || echo "Server not running"
      - docker container rm mazelike || echo "Container not found"
      - docker run --name mazelike -d -p 80:3000 --env-file /etc/mazelike/.env "mazelike/backend:$VERSION"
  only:
    - master

MazeLike_Staging:
  stage: deploy
  script:
      # Version parser from https://gist.github.com/DarrenN/8c6a5b969481725a4413
      - docker build -t "mazelike/backend:staging" .
      - docker kill mazelike_staging || echo "Server not running"
      - docker container rm mazelike_staging || echo "Container not found"
      - docker run --name mazelike_staging -d -p 8080:3000 --env-file /etc/mazelike/staging.env "mazelike/backend:staging"
  only:
    - staging