MazeLike_Tests:
  stage: test
  script:
    - npm start > server.log 2>&1 &
    - npm test
    - kill $!
    - cat server.log
    - rm -f server.log

MazeLike_Deploy:
  stage: deploy
  script:
      # Version parser from https://gist.github.com/DarrenN/8c6a5b969481725a4413
      - "VERSION=$(cat package.json | grep version | head -1  | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
      - docker build -t "mazelike/backend:$VERSION" .
      - docker tag "mazelike/backend:$VERSION" mazelike/backend:latest
      - docker kill mazelike || echo "Server not running"
      - docker container rm mazelike || echo "Container not found"
      - docker run --name mazelike -d -p 80:3000 --env-file /etc/mazelike/.env "mazelike/backend:$VERSION"
  only:
    - master