stages:
  - build
  - test
  - cleanup
  - deploy

Build:
  stage: build
  script:
    - sed s/latest/branch-$CI_COMMIT_REF_NAME/ -i docker-compose.yml
    - docker-compose build
    - docker-compose up -d backend

Eslint:
  stage: test
  script:
    - npm run eslint

Backend_Tests:
  stage: test
  script:
    - sed s/latest/branch-$CI_COMMIT_REF_NAME/ -i docker-compose.yml
    - touch runner-result
    - docker-compose up -d
    - node scripts/test-stopper.js

Browser_Tests:
  stage: test
  script:
    # Version parser from https://gist.github.com/DarrenN/8c6a5b969481725a4413
    - sed s/ryan3r\\/mazelike_tests:latest/ryan3r\\/mazelike_browser_tests:alpine/ -i docker-compose.yml
    - touch runner-result
    - chmod 666 runner-result
    - docker-compose up -d
    - node scripts/test-stopper.js

Version_Change:
  stage: test
  allow_failure: true
  script:
    - node scripts/version-check.js

Cleanup:
  stage: cleanup
  when: always
  script:
    - docker-compose down

Deploy:
  stage: deploy
  script:
      - VERSION=$(cat VERSION)
      - node scripts/version-check.js
      - docker tag ryan3r/mazelike:branch-$CI_COMMIT_REF_NAME ryan3r/mazelike:$VERSION
      - deploy $VERSION
      - docker tag ryan3r/mazelike:$VERSION ryan3r/mazelike:latest
  only:
    - master
