cache:
  paths:
   - docker-compose.yml
   - node_modules

Mazelike_Build:
  stage: build
  script:
   - mv package.json _package.json
   - npm i handlebars --no-package-lock
   - mv _package.json package.json
   - node scripts/gen-compose -version branch-$CI_COMMIT_REF_NAME -test -suffix -test-$CI_COMMIT_REF_NAME
   - docker-compose build

MazeLike_Tests:
  stage: test
  script:
   - mkdir runner-result
   - docker-compose up -d
   - node scripts/test-stopper.js || (docker-compose down --rmi all && exit 1)

MazeLike_Deploy:
  stage: deploy
  script:
      # Version parser from https://gist.github.com/DarrenN/8c6a5b969481725a4413
      - "VERSION=$(cat package.json | grep version | head -1  | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
      - node scripts/version-check.js
      - docker-compose -f /etc/mazelike/docker-compose.yml down || echo "No compose file"
      - docker kill $(docker ps -f label=edu.iastate.ryanr=mazelike- -q) || echo "No Games"
      - node scripts/gen-compose -version $VERSION -env_file
      - docker tag ryan3r/mazelike:branch-$CI_COMMIT_REF_NAME ryan3r/mazelike:$VERSION
      - docker tag ryan3r/mazelike:$VERSION ryan3r/mazelike:latest
      - cp docker-compose.yml /etc/mazelike
      - docker-compose up -d
      - push Master "Deployed version $VERSION"
  only:
    - master
