MazeLike_Testing:
  image: node:8.11
  stage: test
  script:
    - npm install -dd
    - npm run eslint
    - npm test

MazeLike_Deploy:
  image: docker:stable
  stage: deploy
  script:
      # Version parser from https://gist.github.com/DarrenN/8c6a5b969481725a4413
      - "VERSION=$(cat package.json | grep version | head -1  | awk -F: '{ print $2 }' | sed 's/[\",]//g')"
      - docker build -t \"mazelike/backend:$VERSION\" .
      - docker kill mazelike || echo "Server not running"
      - docker container rm mazelike || echo "Container not found"
      - docker run --name mazelike -d -p 80:3000 -e NODE_ENV=production \"mazelike/backend:$VERSION\"
