# Version parser from https://gist.github.com/DarrenN/8c6a5b969481725a4413
cache:
  paths:
   - docker-compose.yml

Mazelike_Build:
  stage: build
  script:
   - sed s/latest/branch-$CI_COMMIT_REF_NAME/ -i docker-compose.yml
   - docker-compose build

MazeLike_Tests:
  stage: test
  script:
   - touch runner-result
   - docker-compose up -d
   - node scripts/test-stopper.js || (docker-compose down --rmi all && exit 1)

MazeLike_Deploy:
  stage: deploy
  script:
      - "VERSION=$(cat package.json | grep version | head -1  | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
      # - node scripts/version-check.js
      - docker tag ryan3r/mazelike:branch-$CI_COMMIT_REF_NAME ryan3r/mazelike:$VERSION
      - deploy $VERSION
      - push Master "Deployed version $VERSION"
  only:
    - master
    - ryanr_docker
