branches:
    only:
        master

addons:
  chrome: stable

services:
    - docker

language: node_js
node_js:
    - "8"

stages:
    - test

before_install:
    - docker build -t ryan3r/mazelike .
    - docker run --rm -d -p 127.0.0.1:3000:3000 ryan3r/mazelike
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

jobs:
    include:
        - stage: "test"
          name: "eslint"
          script:
            - npm run eslint
        - script:
            - npm test
          name: "Backend Tests"
        - script:
            - node scripts/version-check.js
          name: "Verision Change"
        - script:
            - npm run browser-test
          name: "Browser tests"