branches:
    only:
        master

services:
    - docker

language: node_js
node_js:
    - "8"

stages:
  - build
  - test
  - cleanup

jobs:
    include:
        - stage: "build"
          script:
            - docker --version
        - stage: "test"
          name: "eslint"
          script:
            - npm i
            - npm run eslint
        - script:
            - touch runner-result
            - chmod 666 runner-result
            - docker-compose up -d
            - node scripts/test-stopper.js tests_backend
          name: "Backend Tests"
        - script:
            - node scripts/version-check.js
          name: "Verision Change"
