version: "3.2"
services:
  backend:
    image: mazelike/backend:devel
    build:
      context: .
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mazelike
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    networks:
      - backend
    ports:
      - 5506:3306

volumes:
  mysql-data:

networks:
  backend:
