# NOTE: This is file is for testing
version: "3.2"
services:
  backend:
    image: ryan3r/mazelike:latest
    build:
      context: .
    environment:
      DB_STORAGE: ":memory:"
      CLUSTER_MANAGER: none
    expose:
      - 3000
    networks:
      - mazelike_testing

  tests:
    image: ryan3r/mazelike_tests:latest
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - backend
    networks:
      - mazelike_testing
    environment:
      IS_RUNNING_IN_DOCKER: ok
    volumes:
      - type: bind
        source: ./runner-result
        target: /usr/src/app/runner-result
      - type: bind
        source: ./scripts
        target: /usr/src/app/scripts

networks:
  mazelike_testing:
