# NOTE: This is file is for testing
version: "3.2"
services:
  backend:
    image: ryan3r/mazelike:latest
    build:
      context: .
    expose:
      - 3000
    networks:
      - mazelike_testing_branch

  tests_backend:
    image: ryan3r/mazelike_tests:latest
    build:
      context: tests
    command: backend
    networks:
      - mazelike_testing_branch
    environment:
      IS_RUNNING_IN_DOCKER: ok
      BACKEND: backend_branch
    volumes:
      - type: bind
        source: ./runner-result
        target: /usr/src/app/runner-result
      - type: bind
        source: ./tests/spec
        target: /usr/src/app/spec
  
  tests_browser:
    container_name: tests_branch_browser
    image: ryan3r/mazelike_tests:latest
    build:
      context: tests
    command: browser
    networks:
      - mazelike_testing_branch
    environment:
      IS_RUNNING_IN_DOCKER: ok
      BACKEND: backend_branch
    volumes:
      - type: bind
        source: ./runner-result
        target: /usr/src/app/runner-result
      
networks:
  mazelike_testing_branch:
