version: "3.2"
services:
    backend:
        image: mazelike/backend
        build:
            context: .
        env_file: .env
        ports:
            - 3000:3000
        depends_on:
            - mysql
        networks:
            - backend

    mysql:
        image: mysql:5
        env_file: .env
        restart: always
        volumes:
            - type: volume
              source: mysql-data
              target: /var/lib/mysql
        networks:
            - backend
        expose:
            - 3306

volumes:
    mysql-data:

networks:
    backend:
