version: "3.2"
services:
  backend:
    container_name: testing_backend
    image: mazelike/backend:devel
    build:
      context: .
    environment:
      DB_STORAGE: ":memory:"
    expose:
      - 3000
    networks:
      - testing

  tests:
    container_name: testing_tests
    image: mazelike/tests
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - backend
    networks:
      - testing
    environment:
      IS_RUNNING_IN_DOCKER: ok
    volumes:
      - type: bind
        source: ./runner-result
        target: /app/runner-result

networks:
  testing:
