# NOTE: This is file is for testing
version: "3.2"
services:
  backend:
    container_name: backend_branch
    image: ryan3r/mazelike:latest
    build:
      context: .
    environment:
      DB_STORAGE: ":memory:"
      CLUSTER_MANAGER: none
    expose:
      - 3000
    networks:
      - mazelike_testing_branch

  tests:
    container_name: tests_branch
    image: ryan3r/mazelike_tests:latest
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - backend
    networks:
      - mazelike_testing_branch
    environment:
      IS_RUNNING_IN_DOCKER: ok
      BACKEND: backend_branch
    volumes:
      - type: bind
        source: ./runner-result
        target: /usr/src/app/runner-result
      - type: bind
        source: ./scripts
        target: /usr/src/app/scripts

networks:
  mazelike_testing_branch:
