version: "3.2"
services:
  backend:
    image: mazelike/backend:devel
    build:
      context: .
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: password
      DB_DATABASE: mazelike
    expose:
      - 3000
    depends_on:
      - mysql
    networks:
      - testing

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mazelike
      MYSQL_ROOT_PASSWORD: password
    networks:
      - testing
    expose:
      - 3306
  
  tests:
    image: mazelike/tests
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - backend
    networks:
      - testing
    environment:
      IS_RUNNING_IN_DOCKER: ok

networks:
  testing:
