# NOTE: This is file is for testing
version: "3.2"
services:
  backend:
    image: ryan3r/mazelike:latest
    build:
      context: .
    environment:
      DB_STORAGE: ":memory:"
      CLUSTER_MANAGER: none
    expose:
      - 3000
    networks:
      - mazelike_testing

  tests:
    image: ryan3r/mazelike_tests:latest
    build:
      context: tests
    command: backend
    networks:
      - mazelike_testing
    environment:
      IS_RUNNING_IN_DOCKER: ok
      BACKEND: backend
    volumes:
      - type: bind
        source: ./runner-result
        target: /usr/src/app/runner-result
      - type: bind
        source: ./spec
        target: /usr/src/app/spec
      
networks:
  mazelike_testing:
