version: "3.2"
services:
    backend:
        image: mazelike/backend
        build:
            context: .
        env_file: .env
        ports: 
            - 3000:3000
        depends_on:
            - mysql
        networks:
            - backend
        volumes:
            - type: volume
              source: mysql-con
              target: /var/run/mysqld


    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        env_file: .env
        restart: always
        volumes:
            - type: volume
              source: mysql-data
              target: /var/lib/mysql
            - type: volume
              source: mysql-con
              target: /var/run/mysqld
        networks:
            - backend

volumes:
    mysql-data:
    mysql-con:

networks:
    backend:

