version: "3.2"
services:
  backend:
    image: mazelike/backend:devel
    build:
      context: .
    env_file: .env
    expose:
      - 3000
    depends_on:
      - mysql
    networks:
      - testing

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mazelike
      MYSQL_ROOT_PASSWORD: password
    networks:
      - testing
    expose:
      - 3306
  
  tests:
    image: mazelike/tests
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - backend
    networks:
      - testing

networks:
  testing:
