version: "3.2"
services:
  master:
    image: mazelike
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./data
        target: /data

  minion1:
    hostname: minion1
    image: mazelike
    environment:
      MAZELIKE_EXTERN_ADDR: localhost:5900
      MAZELIKE_MASTER: http://master
      LOG_LEVEL: verbose
    ports:
      - 5900:3000
    volumes:
      - type: bind
        source: ./data
        target: /data
  
  minion2:
    hostname: minion2
    image: mazelike
    environment:
      MAZELIKE_EXTERN_ADDR: localhost:5901
      MAZELIKE_MASTER: http://master
      LOG_LEVEL: verbose
    ports:
      - 5901:3000
    volumes:
      - type: bind
        source: ./data
        target: /data